### ISSUE TITLE
In Observation auch andere Typen außer Quantity erlauben

### ISSUE THREAD

**Issue by noemide** [medizininformatik-initiative/kerndatensatzmodul-labor#1]
Es gibt LONIC-codierte Tests, deren Ergebnis nicht numerisch sondern z.B. positiv/negativ oder "+"/"++" usw. ist. Man sollte deshalb weitere Datentypen als Value erlauben, evtl. sogar string als "last resort" für sonst nicht codierbare Werte. Zitat ArtDecor Definition: "Wert der Analyse. Verschiedene Datentypen wie Quantität, Proportion, Ordinalskala oder Freitext möglich, auch in Kombination mit Einheiten."

**Comment by alexzautke** [comment]
Issue wird verschoben und weiter in Simplifier diskutiert:
https://simplifier.net/medizininformatikinitiative-laborprofile/~issues/513
