### ISSUE TITLE
identifier.type nicht Teil des ValueSets

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-labor#10]
[Eric Thomas](https://simplifier.net/user/ericthomas1) commented about a year ago
Das identifier.type Attribut besitzt noch immer das Binding für das Standard ValueSet: "https://www.hl7.org/fhir/valueset-identifier-type.html". Dadurch ist der code "OBI" nicht zulässig und wird durch die FHIR-Validierung als nicht Teil des ValueSets erkannt. Kann an dieser STelle das ValueSet erweitert werden?

**Comment by julsas** [comment]
`Warning @ Observation.identifier[0].type (line 11, col8): None of the codings provided are in the value set 'IdentifierType' (http://hl7.org/fhir/ValueSet/identifier-type|4.0.1), and a coding should come from this value set unless it has no suitable code (note that the validator cannot judge what is suitable) (codes = http://terminology.hl7.org/CodeSystem/v2-0203#OBI)`

If **there is no applicable concept** in value set (based on human review), an alternate concept (either system/code pair, or text) may be used instead. http://hl7.org/fhir/r4/terminologies.html#extensible

Ich würde es so belassen und die Warnung ignorieren.

**Comment by alexzautke** [comment]
OBI sollte zusammen mit allen anderen Code in einem eigenen ValueSet and Observation.identifier.type gebunden werden.

**Comment by julsas** [comment]
v2-0203#OBI jetzt in ValueSet  auf Observation.identifier.type und Validator wirft keine keine Warning mehr.
Getestet mit Java Validator v6.2.15
