### ISSUE TITLE
Abgleich mit dem HL7 EU-Laborbericht

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-labor#12]
Siehe https://hl7.eu/fhir/laboratory/0.1.0-ballot/

**Comment by julsas** [comment]
# Version 0.1.0-ballot
## DiagnosticReport: Laboratory Report
- .extension 1..1 http://hl7.org/fhir/5.0/StructureDefinition/extension-DiagnosticReport.composition 
- .category 0..* mit optional coding slices und vs binding; 26436-6 aus MII-Profil memberOf(LabStudyTypesEuVs); kein v2-0074
- .code beide LOINC 11502-2
- .effective[x] 0..1
- .issued 0..1
- .result 0..*

##  ServiceRequest: Laboratory Order
- .category 0..* und keine Coding Requirements
- .authoredOn 0..1

## Observation Results: laboratory
- .identifier 0..*
- .category.coding mit 1..1 slice wie MII und optionalen slices 26436-6 aus MII-Profil memberOf(LabStudyTypesEuVs)
- .performer 1..*
- .value[x] mehr data types erlaubt; valueCodeableConcept Bindings
- eu-lab-1 und eu-lab-2 constraints
