### ISSUE TITLE
Modul auch für Untersuchungen an Auge, Ohr etc. verwendbar?

### ISSUE THREAD

**Issue by hoffmka** [medizininformatik-initiative/kerndatensatzmodul-labor#22]
Meine Aufgabe ist, Untersuchungsergebnisse aus der Augenheilkunde mittels MII FHIR Spezifikationen abzubilden. Das sind z.B. die Sehstärke oder der Augeninnendruck. Die Frage ist, ob das Basismodul Labor für solche Untersuchungen vorgesehen ist. Wenn ja, wo würde man hinterlegen, welches Auge (rechts oder links) untersucht wurde. Das Element "bodysite" steht ja hier nicht zur Verfügung. 
Diese Frage müsste sich bei allen Untersuchungen an paarig vorkommenden Körperteilen, wie Ohr, Arm, Bein, ... stellen. Sind diese Untersuchungen mit dem Modul Labor abbildbar oder gibt es ein anderes, dafür geeignetes Modul oder müssen hierfür Erweiterungsmodule entwickelt werden?

Viele Grüße,
Katja Hoffmann

**Comment by patrick-werner** [comment]
Vielen Dank für die Frage. 
Das Modul Labor ist für die Abbildung von Laboruntersuchungen gedacht, also die Untersuchung von Werten von Blut, Urin etc.
Für die Augenheilkunde würde es ich anbieten entweder ein Modul Augenheilkunde, oder ein generisches Modul welches weitere körperliche Untersuchungen (bspw. Hörtest) abbildet.
