### ISSUE TITLE
Quelle Klinisches Bezugsdatum

### ISSUE THREAD

**Issue by SevKohler** [medizininformatik-initiative/kerndatensatzmodul-labor#23]
Hey,

ich wunder mich etwas über das Bezugsdatum. 
![image](https://github.com/user-attachments/assets/4f2d6aba-a21c-4d99-9902-4b001783760c)

Die extension ist ein reines coding, es wird also kein extra Datum spezifiziert. 
Damit ist das Bezugsdatum einfach nur eine Art "tag" der sagt entweder Anforderungszeitpunkt oder Laboreingangszeitpunkt sind Klinisches Bezugsdatum?
Warum ist das dann nicht beim Specimen extended.
Oder ersetzt das dann das effective mit einem duplikat aus dem Specimen falls der Code gesetzt, was ja semantisch nicht ganz sauber wäre ? 

Der IG gibt leider auch nicht soviel her. 

VG

**Comment by alexzautke** [comment]
@patrick-werner @FErdfelder Könnt ihr dieses Thema bei einem nächsten Treffen besprechen?

**Comment by Marfede** [comment]
Lieber Hr Kohler,

sie haben vollkommen recht, der Bezugszeitpunkt selbst ist nicht Observation.effective[x].extension, sondern Observation.effective[x].

zur extension:
Die Extension dient zur Differenzierung, ob als Bezugsdatum der Entnahmezeitpunkt (eigentlicher Bezugszeitpunkt, der aber meist nicht oder nur sehr schlecht dokumentiert vorliegt) oder der Laboreingangszeitpunkt verwendet wurde.
Im Zusammenhang ihres Kommentars fiel uns auf, dass noch eine dazu parallele extension bei DiagnosticReport.effective fehlt.

zu den specimen-Zeitpunkten:
Die Zeitpunkte Entnahme (Specimen.collected[x]) und Probeneingang (Specimen.recievedTime) werden als Eigenschaft der Probe modelliert. Das macht inhaltlich auch mehr Sinn, als sie primär unter Observation oder DiagnosticReport unterzubringen.
Dabei sind beides Zeitpunkte, die jeweils dokumentiert werden sollten, wenn sie verfügbar sind. Deswegen werden diese beiden Items meines Wissens auch keine Pflichtangaben, während die Observation.effective notwendig für den KDS ist (1..1).

zu den dadurch entstehenden redundanten Daten:
Da als klinischer Bezugszeitpunkt aber einer dieser beiden verwendet werden soll und dieser Zeitpunkt so zentral für die Interpretation jedes einzelnen Laborwerts ist, soll dieser trotzdem auch direkt in der Observation auftauchen und somit leider eine Redundanz bilden. Diese Redundanz ist somit zum Teil 3-fach, wenn für den Probeneingangszeitpunkt sowohl Specimen.recievedTime, als auch DiagnosticReport.effective und Observation.effective verwendet wird.


Im aktuellen Entwurf des IGs habe ich versucht, das klarer zu beschreiben. Obige Tabelle sieht aktuell wie untenstehend aus - gern noch Anmerkungen. Die komplette Überarbeitung der Zeitpunktbeschreibung schicke ich die Tage an das Team Laborbefund zur Finalisierung des Textes vorraussichtlich bis 06.09.24.

VG

![image](https://github.com/user-attachments/assets/0a8276ab-52bd-4963-aade-9f2bd5928028)

**Comment by SevKohler** [comment]
Also:
Wenn die Probenentnahme/.. da ist, wird das duplikat in Observation und DiagnosticReport.effective gesetzt zusätzlich. 
Falls nicht wird die normale effective genommen. 
Ist das nicht etwas das ganz klar governance ist ?
So überschreibt ihr ja sematnisch inkorrekt Felder.
Specimen hat ja perse auch keine required felder, ihr könnt ja die z.B. collected oä immer setzen wenn vorhanden. 
 
Governance:
Ist specimen da bitte nehmt Zeitpunkt X. 
Falls nicht gibts eh nur effective.

**Comment by Marfede** [comment]
Wir nehmen die Anmerkungen noch mal mit in die Besprechung - gern dazu kommen! - 06.09. 12:30
Folgende Rückfragen von mir direkt:
1.) Was heißt "normale" effective? "Normal" bzw. eher "inhaltlich am ehesten korrekt" wäre ja die Probenentnahme?

2.) Was genau wird aus ihrer Sicht semantisch inkorrekt überschrieben? Wie konkret wäre es semantisch korrekt zu lösen?

Anmerkung meinerseits: "immer setzen wenn vorhanden" ist gefährlich, da "vorhanden" nicht immer auch "ausreichende Dokumentationsqualität" bedeutet. Außerdem heißt vorhanden auch nicht "immer vorhanden" und das wird dazu führen, dass man von einem Standort bzw. einer Datenquelle manchmal eine Abnahmezeit hätte und manchmal nicht.
Deswegen wird in der Beschreibung weiterführend darauf eingegangen werden:

"Optimalerweise liegt ein gut dokumentierter Entnahmezeitpunkt vor und kann so als klinischer Bezugszeitpunkt verwendet werden. In vielen Fällen reicht die Dokumentationsqualität von Entnahmezeitpunkten allerdings nicht aus, sodass häufig der Laboreingangszeitpunkt oder ggf. andere Zeitpunkte (z.B. geschätzter/berechneter Entnahmezeitpunkt) verwendet werden."
... 
"Laboreingangszeotpunkt: ... „Datum und Uhrzeit des Eingangs des Untersuchungsmaterials“ ist einer der zwei Zeitstempel deren Angabe auf dem Laborbefund verpflichtend ist (neben dem Zeitpunkt der Berichtausgabe) – für alle medizinischen Labore in Deutschland (RiLiBÄK 2019/23) und akkreditierte Labore international (DIN EN ISO 15189_2023).
Außerdem wird der Laboreingangszeitpunkt in vielen Laboren mit bereits voretikettierten Proben automatisiert dokumentiert. Dies führt zu einer hohen Dokumentationsqualität und Verfügbarkeit, wodurch sich der Laboreingangszeitpunkt häufig besser als klinischer Bezugszeitpunkt eignet als der Entnahmezeitpunkt. "

--> Hier ist es am ehesten die Aufgabe der jeweiligen DIZn einzuschätzen, welche der zur Verfügung stehenden Zeitstempel am verlässlichsten als Surrogat des Bezugszeitpunkts verwendet werden können - ich nehme an, dass es in den meisten Fällen der Laboreingangszeitpunkt sein wird...
Einen Automatismus im Sinne von "Wenn vorhanden, dann ..." scheint mir da wie gesagt nicht zielführend.

VG

**Comment by patrick-werner** [comment]
wegen Inaktivität geschlossen (bei Bedarf bitte wieder öffnen)
