### ISSUE TITLE
Snapshot missing value[x] slicing

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-labor#3]
Momentan gibt es ein Problem mit den von Simplifier generierten Snapshots z.B. beim Reprofiling mit fsh fehlt auf value[x] der slicing discriminator und rules.

`error Cannot read property 'discriminator' of undefined`

Kann gefixt werden durch hinzufügen im Snapshot von:

```json
                "slicing": {
                    "discriminator": [
                        {
                            "type": "type",
                            "path": "$this"
                        }
                    ],
                    "ordered": false,
                    "rules": "open"
                },
```

**Comment by alexzautke** [comment]
@julsas Bitte einmal im FSH Zulip Stream nachfragen. Der Discriminator für einen Type Slice sollte optional sein.

**Comment by julsas** [comment]
https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Error.20w.2F.20type.20slices.20missing.20discriminator
