### ISSUE TITLE
SARS-CoV-2-RT-PCR und Antikörper

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-labor#5]
Kann ein Profil für SARS-CoV-2-RT-PCR ähnlich: https://simplifier.net/packages/de.gecco/1.0.5/files/415130 aufgenommen werden?

Außerdem SARS-CoV-2 Antikörper ähnlich: https://simplifier.net/packages/de.gecco/1.0.5/files/415278

**Comment by alexzautke** [comment]
@julsas @rinaldie Wir sollten schauen ob wir dies nicht in Modul Mikrobiologie übernehmen

**Comment by rinaldie** [comment]
@alexzautke @julsas  ich würde sagen das haben wir schon als algemein für alle Mikroorganismen:
https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_molekular_diagnostik
https://simplifier.net/medizininformatik-initiative-modul-mikrobiologie/mii_pr_mikrobio_serologie_immunologie
